### ISSUE TITLE
Vprašanje

### ISSUE THREAD

**Issue by JanSifrer** [JanSifrer/Virus-propagation#3]
Pozdravljeni,

imava eno vprašanje in eno težavo:
*  ali obstaja kakšen preprosti način, da shraniš graf kot neko spremenljivko, in ga potem narišeš tam kjer želiš? Kajti sedaj nama program riše grafe v novem oknu, jaz pa bi želel narediti, da ga izriše pod tabelo za vnos podatkov,  ter rad bi še dodal možnost, da bi se vrnil na prejšnji graf (nekako tako kot je v R, ko se v desnem spodnjem okenčku lahko premikaš med grafi).

* težavo pa imava pri `Bindru`, ker nama noče delati. Napiše namreč samo  `error: 500: Internal Server Error`.

Hvala za pomoč, in lepo pozdravljeni,

Jan

**Comment by jaanos** [comment]
Če prav razumem, bo dovolj, da se shrani ena "fiksna" slika - torej ne bo potrebno nanjo dodajati novih elementov. V tem primeru jo lahko shranita v `BytesIO`, podobno kot [tukaj](https://stackoverflow.com/questions/5314707/matplotlib-store-image-in-variable) (primer je za Python 2 - spodaj so posodobljena navodila):

```python
import io, urllib, base64
slika = io.BytesIO()
plt.savefig(slika, format="png")
```

Tako sliko lahko potem pripravita za vključitev na spletno stran:
```python
uri = 'data:image/png;base64,' + urllib.request.quote(base64.b64encode(slika.getbuffer().tobytes()))
```

V predlogi lahko vrednost spremenljivke `uri` potem uporabita kot lokacijo slike, npr.
```jinja
<img src="{{uri}}" />
```

Kar se Binderja tiče, bo potrebno v `requirements.txt` dodati vrstici `matplotlib` in `numpy`, da se namestita ustrezni knjižnici. Vrstico `psycopg2` lahko odstranita, saj ne potrebujeta povezave do baze PostgreSQL. Da bo aplikacija ustrezno delovala na Binderju, bo potrebno poti ustrezno navajati s spremenljivko `ROOT` (podobno kot pri https://github.com/larajagodnik/Avtohisa/blob/master/aplikacija.py).

**Comment by JanSifrer** [comment]
Pozdravljeni,

to je to kar sem želel ja.

Najlepša Vam hvala!
