### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by jaanos** [JanSifrer/Virus-propagation#4]
Vidim, da na repozitoriju nimata datoteke `.gitignore`, tako da se vama je na repozitorij izmuznila mapa `__pycache__`, ki pa tja ne sodi, saj vsebuje avtomatsko generirane datoteke. Najbolje bo, da vzameta kar predlogo za [Python](https://github.com/github/gitignore/blob/master/Python.gitignore). Mapo `__pycache__` seveda pobrišita (lahko kar na GitHubu pobrišeta datoteke v njej).

**Comment by JanSifrer** [comment]
Hvala, sem dodal `.gitignore` in odstranil mapo `__pycache__`
