### ISSUE TITLE
Ključi slovarjev

### ISSUE THREAD

**Issue by jaanos** [JanSifrer/Virus-propagation#5]
Vidim, da za ključe slovarjev uporabljata nize, čeprav ti predstavljajo številske indekse, npr.
https://github.com/JanSifrer/Virus-propagation/blob/c33ab43f15eada30b50a5b7335b69c1a5979e736/generator_tock.py#L25
Ali imata kak poseben razlog za to? Python za ključe dovoli poljubne nespremenljive elemente, med drugim tudi števila. Tako ne vidim razloga, da bi jih vsakič znova spreminjala v nize za potrebe indeksiranja.

Mimogrede, ne glede na to, kakšne indekse uporabljata, gresta lahko čez vrednosti slovarja (tj., ključe z vrednostmi) takole:
```python
for k, v in tocke.items():
    # k je ključ
    # v je ustrezna vrednost
```

Glede na to, da vesta, da so vajine vrednosti četverice, lahko naredita celo tako:
```python
for k, (x, y, status, ze_prebolela) in tocke.items():
    ...
```

**Comment by JanSifrer** [comment]
Pozdravljeni,

ne, ni bilo posebnega razloga za to... V bistvu je ideja za tako indeksiranje izhajala iz tega, da sem mislil, da je ključ lahko samo nek niz... sedaj sem popravil, in vidim da tudi to deluje, tako da je tudi sama koda sedaj malo lepša. Prav tako je pa tudi tale `for` zanka malo pospešila sam program, tako da se Vam res najlepše zahvaljujem! 

Lep pozdrav, 
Jan
